/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
  light: {
    background: "hsl(144, 35%, 95%)",
    foreground: "hsl(0, 0%, 18%)",
    card: "hsl(144, 35%, 95%)",
    cardForeground: "hsl(0, 0%, 18%)",
    popover: "hsl(144, 35%, 95%)",
    popoverForeground: "hsl(0, 0%, 18%)",
    primary: "hsl(144, 35%, 73%)",
    primaryForeground: "hsl(0, 0%, 18%)",
    secondary: "hsl(208, 48%, 65%)",
    secondaryForeground: "hsl(0, 0%, 18%)",
    muted: "hsl(144, 35%, 90%)",
    mutedForeground: "hsl(0, 0%, 45%)",
    accent: "hsl(21, 67%, 81%)",
    accentForeground: "hsl(0, 0%, 18%)",
    destructive: "hsl(0, 80%, 57.70%)",
    destructiveForeground: "hsl(0, 0%, 100%)",
    border: "hsl(144, 20%, 85%)",
    input: "hsl(144, 20%, 85%)",
    ring: "hsl(144, 35%, 73%)",
  },
  dark: {
    background: "hsl(0, 0%, 12%)",
    foreground: "hsl(144, 35%, 90%)",
    card: "hsl(0, 0%, 15%)",
    cardForeground: "hsl(144, 35%, 90%)",
    popover: "hsl(0, 0%, 15%)",
    popoverForeground: "hsl(144, 35%, 90%)",
    primary: "hsl(144, 25%, 60%)",
    primaryForeground: "hsl(0, 0%, 12%)",
    secondary: "hsl(208, 35%, 50%)",
    secondaryForeground: "hsl(144, 35%, 90%)",
    muted: "hsl(0, 0%, 20%)",
    mutedForeground: "hsl(144, 15%, 65%)",
    accent: "hsl(21, 55%, 70%)",
    accentForeground: "hsl(0, 0%, 12%)",
    destructive: "hsl(0, 62.80%, 30.60%)",
    destructiveForeground: "hsl(0, 85.70%, 97.30%)",
    border: "hsl(0, 0%, 25%)",
    input: "hsl(0, 0%, 25%)",
    ring: "hsl(144, 25%, 60%)",
  },
};
